[package]
name = "full_text_search"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
dotenvy = "0.15"
futures = "0.3.28"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
sqlx = { version = "0.7", features = ["runtime-tokio-native-tls", "postgres", "json"] }
tantivy = "0.19"
tempfile = "3.8.0"
tokio = { version = "1.32.0", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["sync"] }
